### PR TITLE
Make it Python 3 compatible

### PR DESCRIPTION
**Pull request by nagylzs**
The most important change is to replace this:

pixels = b''.join((b''.join(map(chr, pix)) for pix in rgbpixels))

into this:

pixels = b''.join((b''.join(map(bytearray, pix)) for pix in rgbpixels))

The chr function works in python 2 only. The bytearray works in both python 2 and 3.

By accedient, I have also reformatted the code to conform to PEP 8 (replace tabs with 4 spaces). If you would not like to do that please write me and I'm goint to send a new PR that only changes that one line in the code.

### CODE REVIEW

**Comment by tshirtman** [comment]
Sorry for long delay, didn't watch the garden closely, thanks for the fix!

**Comment by AndreMiras** [comment]
Thanks for the PR!
For records, I do like PEP8 formatting, but I think it's the exact case where it deserves two commits. Because otherwise it's hard to review what's the change is doing.
I understood it was by accident, but if the change was just the `pixels` line you shared. Next time it's easy to simply reset the change, do the two commits and push force.

**Comment by nagylzs** [comment]
Yes, I'm sorry. :-(

**Comment by AndreMiras** [comment]
No worry, thank you very much for your contribution!

**Pull request merged**
